"""4th - working on bug fix

Revision ID: 2ed32dd30cd1
Revises: ad5620afad84
Create Date: 2023-06-16 16:34:59.217912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ed32dd30cd1'
down_revision = 'ad5620afad84'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
