"""3rd - changed repr to be more clear, will test if relations are correct

Revision ID: ad5620afad84
Revises: 2582e8b0e692
Create Date: 2023-06-16 15:19:30.637987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad5620afad84'
down_revision = '2582e8b0e692'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
