"""5th - trying to fix bug in data base

Revision ID: b809fae0d6ea
Revises: 2ed32dd30cd1
Create Date: 2023-06-16 16:37:33.683167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b809fae0d6ea'
down_revision = '2ed32dd30cd1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
