"""Added 2 more tables, servers and worlds

Revision ID: e96494afe789
Revises: c81e4eaf8cc9
Create Date: 2023-06-15 11:21:26.251967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e96494afe789'
down_revision = 'c81e4eaf8cc9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worlds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('spawn', sa.Integer(), nullable=True),
    sa.Column('player_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worlds')
    op.drop_table('servers')
    # ### end Alembic commands ###
